import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import type { AppProps } from 'next/app'
import { GeneralContainer, Container } from '../styles/general'

const Home: React.FC<AppProps> = ({ Component, pageProps }) => {
  return (
    <div>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GeneralContainer>
        <Container>
          <h2>Menu Principal</h2>

          <ul>
          <li><Link href="/list">Listagem de transações</Link></li>
          <li><Link href="/transaction">Cadastrar Transação</Link></li>
        </ul>

        </Container>
      </GeneralContainer>

    </div>
  )
}
export default Home
